<?php require 'templates/layout/header.phtml' ?>
<!-- Formulario para editar juegos -->

<h1>Platform to edit.</h1>
<b><?= $platform->nombrePlataforma ?></b> | <b><?=$platform->fabricante?></b>
<form action="editarPlataforma" method="POST" class="my-4">
    <input type="hidden" name="platform_id" value="<?= $platform->id_plataforma ?>">
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label>Plataforma</label>
                <input required name="plataforma" type="text" class="form-control">
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label>Fabricante</label>
                <input required name="compania" type="text" class="form-control">
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label>Tipo (pc,consola ,etc)</label>
                <input required name="tipo" type="text" class="form-control">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>