<?php require 'templates/layout/header.phtml' ?>
<!-- Formulario para editar juegos -->

<h1>Game to edit.</h1>
<b><?= $game->titulo ?></b> | <b><?=$game->genero?></b> 
<form action="editar" method="POST" class="my-4">
    <!--Envio el id del juego de forma oculta-->
    <input type="hidden" name="game_id" value="<?= $game->id_videojuego ?>">
    <div class="row">
        <div class="col-7">
            <div class="form-group">
                <label>Título</label>
                <input required name="title" type="text" class="form-control">
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label>Genero</label>
                <select required name="genre" class="form-control">
                    <option value="Accion">Accion</option>
                    <option value="Carreras">Carreras</option>
                    <option value="Multijugador">Multijugador</option>
                    <option value="Estrategia">Estrategia</option>
                    <option value="Deportes">Deportes</option>
                </select>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>