<?php require 'templates/layout/header.phtml' ?>

<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-7">
            <div class="form-group">
                <label>Título</label>
                <input required name="title" type="text" class="form-control">
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label>Plataforma</label>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label>Empresa que la creo</label>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>