<?php require 'templates/layout/header.phtml' ?>
<!-- Formulario para Agregar juegos -->

<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-7">
            <div class="form-group">
                <label>Título</label>
                <input required name="title" type="text" class="form-control">
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label>Genero</label>
                <!-- HACER ESTO CON UN FOR -->
                <select required name="genre" class="form-control">
                    <option value="Accion">Accion</option>
                    <option value="Carreras">Carreras</option>
                    <option value="Multijugador">Multijugador</option>
                    <option value="Estrategia">Estrategia</option>
                    <option value="Deportes">Deportes</option>
                </select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label>Plataforma</label>
                <!-- HACER ESTO CON UN FOR -->
                <select required name="platform" class="form-control">
                    <option value="1">Steam</option>
                    <option value="2">Playstation</option>
                    <option value="3">Xbox</option>
                    <option value="4">Epic Games</option>
                </select>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>

<?php require 'templates/layout/footer.phtml' ?>