<?php require 'templates/layout/header.phtml' ?>

<div class="px-4 py-5 my-5 text-center">
    <img class="d-block mx-auto mb-4" src="./img/logo.jpg" alt="" width="20%" height="20%">
    <h1 class="display-5 fw-bold">GamesNight</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Jero cabezaPene</p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <button type="button" class="btn btn-danger btn-lg px-4 gap-3" onclick="window.location.href='listarJuegos';">Games list</button>
        <button type="button" class="btn btn-warning btn-lg px-4" onclick="window.location.href='listarPlataformas';">Platform List</button>
    </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml' ?>