<?php require 'templates/layout/header.phtml' ?>

<div class="p-3 mb-2 bg-dark text-white">Platforms List!</div>
<ul class="list-group">
<?php foreach($platforms as $platform): ?>
  <li class="list-group-item">
  <div class="label">
    <b><?= $platform->nombrePlataforma ?></b> | <b><?=$platform->fabricante?> </b>
  </div>
  <div class="actions">
        <a href="formEditarPlataforma/<?= $platform->id_plataforma ?>" type="button" class='btn btn-success btn-sm ml-auto'>Edit</a> 
        <a href="eliminarPlataforma/<?= $platform->id_plataforma ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Delete</a>
  </li>
<?php endforeach ?> 
</ul>

<p class="mt-3"><small>Showing <?=$count?> Platforms</small></p>
<?php require 'templates/layout/footer.phtml' ?>
