<?php require 'templates/layout/header.phtml' ?>

<div class="p-3 mb-2 bg-dark text-white">Games List!</div>

<ul class="list-group">
  <?php foreach($games as $game): ?>
    <li class="list-group-item item-task">
      <div class="label">
        <b><?= $game->titulo ?></b> | <b><?=$game->genero?></b> 
      </div>
      <div class="actions">
        <a href="formEditar/<?= $game->id_videojuego ?>" type="button" class='btn btn-success btn-sm ml-auto'>Edit</a> 
        <a href="borrar/<?= $game->id_videojuego ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Delete</a>
    </div>
    </li>
  <?php endforeach ?>
</ul>

<p class="mt-3"><small>Showing <?=$count?> games</small></p>

<?php require 'templates/layout/footer.phtml' ?>