<?php require 'templates/layout/header.phtml' ?>

<?php require 'templates/form_alta_tarea.phtml' ?>

<ul class="list-group">
<?php foreach($games as $game): ?>
    <li class="list-group-item item-task <?php if($game->finalizada): ?> finished <?php endif ?>">
        <div class="label">
            <b><?= $game->titulo ?></b> | <?=substr($game->descripcion,0,25)?> | (Prioridad <?= $game->prioridad ?>)
        </div>
        <div class="actions">
            <?php if(!$game->finalizada): ?> 
                <a href="finalizar/<?= $game->id ?>" type="button" class='btn btn-success btn-sm ml-auto'>Finalizar</a> 
            <?php endif ?>
            <a href="eliminar/<?= $game->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> games</small></p>


<?php require 'templates/layout/footer.phtml' ?>
