<?php require 'templates/layout/header.phtml' ?>

<div class="p-3 mb-2 bg-dark text-white">Platforms List!</div>
<ul class="list-group">
<?php foreach($platforms as $platform): ?>
  <div><li class="list-group-item"><b><?= $platform->nombrePlataforma ?></b> | <?=$platform->fabricante?></li></div>
  <div class="actions">
        <a href="formEditar/<?= $game->id_plataforma ?>" type="button" class='btn btn-success btn-sm ml-auto'>Edit</a> 
        <a href="borrar/<?= $game->id_plataforma ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Delete</a>
    </div>
  <?php endforeach ?> 
  </ul>

<p class="mt-3"><small>Showing <?=$count?> Platforms</small></p>
<?php require 'templates/layout/footer.phtml' ?>
