<!DOCTYPE html>
<html lang="en">

<!-- head -->
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Titulo</title>
</head>

<body>

    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <!-- Si quiero hacer que esto funcione como un boton es probable que deba usar JavaScript-->
            <span class="fs-4" href="home">GamesNight!</span>
          </a>
          <ul class="nav nav-pills">
            <li class="nav-item"><a href="index" class="nav-link" aria-current="page">Home</a></li>
            <li class="nav-item"><a href="listarJuegos" class="nav-link">Games</a></li>
            <li class="nav-item"><a href="listarPlataformas" class="nav-link">Platforms</a></li>
            <li class="nav-item"><a href="login" class="nav-link">Login</a></li>
          </ul>
        </header>
    </div>